import {
  apiRequest,
} from "./api";

type User = {
  id: string;
  name: string;
  email: string;
  avatar: string | null;
};

type AuthResponse = {
  message: string;
  user: User;
};

type UserResponse = {
  message?: string;
  user: User;
};

type LoginCredentials = {
  email: string;
  password: string;
};

type RegisterData = {
  name: string;
  email: string;
  password: string;
};

type UpdateProfileData = {
  name: string;
  email: string;
};

/*
 * =========================================================
 * LOGIN
 * =========================================================
 */

async function login(
  credentials: LoginCredentials,
) {
  const response =
    await apiRequest<AuthResponse>(
      "/api/auth/login",
      {
        method: "POST",

        body: JSON.stringify(
          credentials,
        ),
      },
    );

  saveSession(
    response,
  );

  return response;
}

/*
 * =========================================================
 * REGISTER
 * =========================================================
 */

async function register(
  data: RegisterData,
) {
  const response =
    await apiRequest<AuthResponse>(
      "/api/auth/register",
      {
        method: "POST",

        body:
          JSON.stringify(
            data,
          ),
      },
    );

  saveSession(
    response,
  );

  return response;
}

/*
 * =========================================================
 * CURRENT USER
 * =========================================================
 */

async function getMe() {
  return apiRequest<UserResponse>(
    "/api/auth/me",
    {
      auth: true,
    },
  );
}

/*
 * =========================================================
 * UPDATE PROFILE
 * =========================================================
 */

async function updateProfile(
  data: UpdateProfileData,
) {
  const response =
    await apiRequest<UserResponse>(
      "/api/auth/me",
      {
        method: "PATCH",

        auth: true,

        body:
          JSON.stringify(
            data,
          ),
      },
    );

  localStorage.setItem(
    "devboard_user",

    JSON.stringify(
      response.user,
    ),
  );

  return response;
}

/*
 * =========================================================
 * LOGOUT
 * =========================================================
 */

async function logout() {
  /*
   * Remove legacy Bearer tokens
   * immediately.
   */

  localStorage.removeItem(
    "devboard_token",
  );

  localStorage.removeItem(
    "devboard_user",
  );

  try {
    await apiRequest<{
      message: string;
    }>(
      "/api/auth/logout",
      {
        method: "POST",
      },
    );
  } catch {
    /*
     * Local UI session has
     * already been cleared.
     */
  }
}

/*
 * =========================================================
 * AUTH STATUS
 * =========================================================
 */

function isAuthenticated() {
  /*
   * HttpOnly cookies cannot be
   * inspected by JavaScript.
   *
   * This is only a UI hint.
   * Backend authorization remains
   * authoritative.
   */

  return Boolean(
    getStoredUser(),
  );
}

/*
 * =========================================================
 * STORED USER
 * =========================================================
 */

function getStoredUser():
  User | null {
  const stored =
    localStorage.getItem(
      "devboard_user",
    );

  if (!stored) {
    return null;
  }

  try {
    return JSON.parse(
      stored,
    ) as User;
  } catch {
    return null;
  }
}

/*
 * =========================================================
 * SAVE SESSION
 * =========================================================
 */

function saveSession(
  response: AuthResponse,
) {
  /*
   * Delete tokens generated by
   * the previous implementation.
   */

  localStorage.removeItem(
    "devboard_token",
  );

  localStorage.setItem(
    "devboard_user",

    JSON.stringify(
      response.user,
    ),
  );
}

/*
 * =========================================================
 * EXPORTS
 * =========================================================
 */

export {
  getMe,
  getStoredUser,
  isAuthenticated,
  login,
  logout,
  register,
  updateProfile,
};

export type {
  User,
};